device: auto

dataset:
  name: "beauty"

model:
  type: bert
  name: Bert4Rec
  params:
    hidden_size: 256
    num_layers: 3
    num_heads: 4
    hidden_dropout: 0.2
    attention_dropout: 0.1
    max_sequence_length: 20

training:
  max_steps: 50000
  warmup_ratio: 0.1
  batch_size: 128
  accumulation_steps: 2
  early_stopping_patience: 5

optimizer:
  name: AdamW
  lr: 0.0005
  weight_decay: 0.005

scheduler:
  name: linear_with_warmup

loss:
  name: CrossEntropyLoss
  params:
    ignore_index: 0

evaluation:
  interval: 500
  metrics:
    - hit_rate
    - ndcg

saving:
  save_best: true
  save_dir: trained_models
  filename: bert_model
  figure_dir: figures